export const projectData = [
  {
    id: 1,
    name: "Casalola",
    category: "Brand Identity",
    subheadline: "Brand Design",
    image: "https://designmox.co/wp-content/uploads/2025/10/casaloal-03.jpg",
    title: "Casalola",
    description: "Brand Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/casaloal-03.jpg",
    projectSummary:
      "Casalola is a premium brand design project that showcases innovative and creative branding solutions. The design emphasizes visual appeal, consistency, and brand storytelling through thoughtful design direction.",
    whatWeDid: "Brand Identity\nLogo Design\nVisual System",
    categories: "BRANDING, DESIGN, IDENTITY",
    projectInfo: {
      brandIdentity: "Brand Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Branding",
      description:
        "Casalola is a premium brand design project that showcases innovative and creative branding solutions. The design emphasizes visual appeal, consistency, and brand storytelling through thoughtful design direction.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-03.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-04.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-05.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-06.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-07.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-08.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-09.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-10.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/Casaloal.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/Casalola-01.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-03.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-04.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/casaloal-05.jpg",
    ],
  },
  {
    id: 2,
    name: "DOMO",
    category: "Brand Design",
    subheadline: "Brand Design Project",
    image: "https://designmox.co/wp-content/uploads/2025/10/242325.jpg",
    title: "DOMO",
    description: "Brand Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/242325.jpg",
    projectSummary:
      "DOMO is a premium brand design project that showcases innovative and creative branding solutions with dynamic visual content including video elements.",
    whatWeDid: "Brand Identity\nVideo Production\nVisual System",
    categories: "DESIGN, BRANDING, MULTIMEDIA",
    projectInfo: {
      brandIdentity: "Brand Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Branding",
      description:
        "DOMO is a premium brand design project that showcases innovative and creative branding solutions with dynamic visual content.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/242325.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/546532.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/42325.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/6452525.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/546464.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/252525.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/54725.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/31313.mp4",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/242325.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/546532.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/42325.jpg",
    ],
  },
  {
    id: 3,
    name: "Ajorra",
    category: "Packaging",
    subheadline: "Packaging Design",
    image: "https://designmox.co/wp-content/uploads/2025/10/5858568.jpg",
    title: "Ajorra",
    description: "Packaging Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/5858568.jpg",
    projectSummary:
      "Ajorra is a premium packaging design project that showcases innovative and creative packaging solutions. The design emphasizes visual appeal, functionality, and brand storytelling through thoughtful packaging design.",
    whatWeDid: "Packaging Design\nBrand Strategy\nVisual Design",
    categories: "PACKAGING, DESIGN, BRANDING",
    projectInfo: {
      brandIdentity: "Packaging Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Packaging",
      description:
        "Ajorra is a premium packaging design project that showcases innovative and creative packaging solutions. The design emphasizes visual appeal, functionality, and brand storytelling through thoughtful packaging design.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/5858568.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/786768.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/675657.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/363636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/86868.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/57557.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/36457.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/33363.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4t4366.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/5858568.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/786768.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/675657.jpg",
    ],
  },
  {
    id: 4,
    name: "ARKO ART CENTER",
    category: "Brand Identity",
    subheadline: "Art Center Brand",
    image: "https://designmox.co/wp-content/uploads/2025/10/74343525.jpg",
    title: "ARKO ART CENTER",
    description: "Art Center Brand",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/74343525.jpg",
    projectSummary:
      "ARKO ART CENTER is a contemporary art center brand that brings together creative expression, cultural innovation, and community engagement. The brand identity reflects artistic sophistication while maintaining accessibility and warmth.",
    whatWeDid: "Brand Identity\nLogo Design\nEnvironmental Design",
    categories: "ART & CULTURE, BRANDING, CREATIVE",
    projectInfo: {
      brandIdentity: "Art Center",
      year: "2025",
      teamMembers: "Creative Direction: Adnan Akif",
      sector: "Art & Culture",
      description:
        "ARKO ART CENTER is a contemporary art center brand that brings together creative expression, cultural innovation, and community engagement. The brand identity reflects artistic sophistication while maintaining accessibility and warmth.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/74343525.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4545636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4353436.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/656466.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/576452.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/423526.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/363636-1.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/35366.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/74343525.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4545636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4353436.jpg",
    ],
  },
  {
    id: 5,
    name: "El Relincho",
    category: "Brand Identity",
    subheadline: "Brand Design",
    image: "https://designmox.co/wp-content/uploads/2025/10/3533636.jpg",
    title: "El Relincho",
    description: "Brand Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/3533636.jpg",
    projectSummary:
      "El Relincho is a premium brand design project that showcases innovative and creative branding solutions. The design emphasizes visual appeal, consistency, and brand storytelling through thoughtful design direction.",
    whatWeDid: "Brand Identity\nLogo Design\nVisual System",
    categories: "BRANDING, DESIGN, IDENTITY",
    projectInfo: {
      brandIdentity: "Brand Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Branding",
      description:
        "El Relincho is a premium brand design project that showcases innovative and creative branding solutions. The design emphasizes visual appeal, consistency, and brand storytelling through thoughtful design direction.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/3533636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/6455646.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/436564.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/365466.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/365466.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/53535.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/46466.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/46336.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/7336.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/3533636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/6455646.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/436564.jpg",
    ],
  },
  {
    id: 6,
    name: "Compani",
    category: "Logo Design",
    subheadline: "Logo Design",
    image: "https://designmox.co/wp-content/uploads/2025/10/567546346.jpg",
    title: "Compani",
    description: "Logo Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/567546346.jpg",
    projectSummary:
      "Compani is a professional logo design project that showcases innovative and creative design solutions. The design emphasizes visual appeal, memorability, and brand storytelling through thoughtful design direction.",
    whatWeDid: "Logo Design\nBrand Identity\nCreative Direction",
    categories: "DESIGN, BRANDING, CREATIVE",
    projectInfo: {
      brandIdentity: "Logo Design",
      year: "2025",
      teamMembers: "Creative Direction: Adnan Akif",
      sector: "Design & Creative",
      description:
        "Compani is a professional logo design project that showcases innovative and creative design solutions. The design emphasizes visual appeal, memorability, and brand storytelling through thoughtful design direction.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/567546346.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/6574363.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4646636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/566464.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/523535.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4t4456.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/567546346.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/6574363.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/4646636.jpg",
    ],
  },
  {
    id: 7,
    name: "Tokri",
    category: "Packaging Design",
    subheadline: "Packaging Design",
    image: "https://designmox.co/wp-content/uploads/2025/10/02123c223098877.67f48cb5a4549.jpg",
    title: "Tokri",
    description: "Packaging Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/02123c223098877.67f48cb5a4549.jpg",
    projectSummary:
      "Tokri is a premium packaging design project that showcases innovative and creative packaging solutions. The design emphasizes visual appeal, functionality, and brand storytelling through thoughtful packaging design.",
    whatWeDid: "Packaging Design\nBrand Strategy\nVisual Design",
    categories: "PACKAGING, DESIGN, BRANDING",
    projectInfo: {
      brandIdentity: "Packaging Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Packaging",
      description:
        "Tokri is a premium packaging design project that showcases innovative and creative packaging solutions. The design emphasizes visual appeal, functionality, and brand storytelling through thoughtful packaging design.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/02123c223098877.67f48cb5a4549.jpg",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    additionalImages: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
  },
  {
    id: 8,
    name: "Cravers",
    category: "Brand Design",
    subheadline: "Brand Design Project",
    image: "https://designmox.co/wp-content/uploads/2025/10/423424.jpg",
    title: "Cravers",
    description: "Brand Design",
    heroImage: "https://designmox.co/wp-content/uploads/2025/10/423424.jpg",
    projectSummary:
      "Cravers is a dynamic brand design project that showcases innovative and creative branding solutions with multimedia content including video elements.",
    whatWeDid: "Brand Identity\nVideo Production\nVisual System",
    categories: "DESIGN, BRANDING, MULTIMEDIA",
    projectInfo: {
      brandIdentity: "Brand Design",
      year: "2025",
      teamMembers: "Design & Strategy: Adnan Akif",
      sector: "Branding",
      description:
        "Cravers is a dynamic brand design project that showcases innovative and creative branding solutions with multimedia content.",
    },
    galleryImages: [
      "https://designmox.co/wp-content/uploads/2025/10/423424.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/634636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/532525.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/463436.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/423424.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/3636.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/363737.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/347373.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/42424.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/34636.mp4",
      "https://designmox.co/wp-content/uploads/2025/10/33636.jpg",
    ],
    additionalImages: [
      "https://designmox.co/wp-content/uploads/2025/10/423424.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/634636.jpg",
      "https://designmox.co/wp-content/uploads/2025/10/463436.jpg",
    ],
  },
]
